#ifndef ALGORITMOS_RASTERIZACAO_POLAR_COORDINATE_CIRCLE_H
#define ALGORITMOS_RASTERIZACAO_POLAR_COORDINATE_CIRCLE_H

void polar_coordinate_circle(int, int, int, char**);
void usePolarCoordinateCircle(char**);

#endif //ALGORITMOS_RASTERIZACAO_POLAR_COORDINATE_CIRCLE_H
