#ifndef ALGORITMOS_RASTERIZACAO_CONSTANTS_H
#define ALGORITMOS_RASTERIZACAO_CONSTANTS_H

#define X_AXIS_SIZE 40 // + 20 | - 20
#define Y_AXIS_SIZE 80 // + 40 | - 40
#define PIXEL_CHAR 42
#define SPACE_CHAR ' '

#endif //ALGORITMOS_RASTERIZACAO_CONSTANTS_H
